[env:m5stack-cardputer-adv]
board = m5stack-stamps3
extends = esp32s3_base
board_build.partitions = partition-table-8MB.csv
upload_protocol = esptool
build_flags = 
  ${esp32_base.build_flags} 
  -D M5STACK_CARDPUTER_ADV
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/m5stack_cardputer_adv
lib_deps = ${esp32_base.lib_deps}
  earlephilhower/ESP8266Audio@2.2.0 # Audio driver, newer version don't work due to changes in file nameing scheme.
  earlephilhower/ESP8266SAM@1.1.0 # Speech synthesizer, required as dependency for ESP8266Audio
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.1.zip
  ;m5stack/M5Cardputer@^1.1.1 # Not really needed, but added for future-proofing.
